### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/rappor-aggregator#3]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/rappor-aggregator/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by Dexterp37** [comment]
@moz-hwine I don't have permissions to do that, looks like. Is there any action for me to take on this, or did you already fix it?

**Comment by moz-hwine** [comment]
Thanks for the follow up -- I disabled the wiki.

No more action needed.
